### ISSUE TITLE
add a link of your problem

### ISSUE THREAD

**Issue by linxuyalun** [Gusabary/Leetcode#1]
I have read your solutions' idea in your `README.md`.

However, I must do the following steps before understanding what you wrote:
```
1. Open leetcode
2. Click the problems button
3. Input the problem number and finally get the description I want
```

I believe add a link to the corresponding problem will be much better, for example:

> the code for [problem 921](https://leetcode.com/problems/minimum-add-to-make-parentheses-valid/).

**Comment by Gusabary** [comment]
Your advice is pretty good!

**Comment by Gusabary** [comment]
I have added the link to corresponding webpages.

**Comment by Gusabary** [comment]
try to BB

**Comment by Gusabary** [comment]
try to BB again

**Comment by linxuyalun** [comment]
you BB you horse？
